name: Auto Generate Image Index

on:
  push:
    paths:
      - '**.webp'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python and Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install Pillow

      - name: Generate JSON Index with Metadata
        run: |
          python3 -c "
          import os, json
          from PIL import Image
          
          results = []
          files = [f for f in os.listdir('.') if f.endswith('.webp')]
          
          def get_num(name):
              try: return int(name.split('.')[0])
              except: return 0
              
          files.sort(key=get_num, reverse=True)
          
          for filename in files:
              try:
                  with Image.open(filename) as img:
                      width, height = img.size
                      results.append({
                          'i': get_num(filename),
                          'w': width,
                          'h': height
                      })
              except Exception as e:
                  print(f'Error processing {filename}: {e}')
                  
          with open('images.json', 'w') as f:
              json.dump(results, f)
          "
          echo "Generated images.json:"
          cat images.json

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images.json
          
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "🚀 Auto-update images list [skip ci]"
            git push
          fi
